/**
 * Seed script — GraphOne
 *
 * Populates the database with realistic AI ecosystem data:
 *   - 20+ investors (Sequoia, a16z, Lightspeed, etc.)
 *   - 50+ AI companies (OpenAI, Anthropic, Mistral, etc.)
 *   - Funding rounds linking companies → investors
 *   - Founders per company
 *   - Products per company
 *   - 100+ news articles with realistic company references
 *   - Company relationship edges
 *
 * Run with:  npm run seed
 *
 * IMPORTANT: Run migrations/001_initial_schema.sql first.
 * This script is idempotent — it uses upsert (ON CONFLICT DO NOTHING)
 * where possible, but it's safest to run against a clean DB.
 */

import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_KEY!,
);

// ─── Helpers ─────────────────────────────────────────────────────────────────

function M(millions: number): number {
  return Math.round(millions * 1_000_000 * 100); // USD cents
}
function B(billions: number): number {
  return Math.round(billions * 1_000_000_000 * 100);
}

async function insert<T extends Record<string, unknown>>(
  table: string,
  rows: T[],
): Promise<T[]> {
  const { data, error } = await supabase
    .from(table)
    .insert(rows)
    .select();

  if (error) {
    console.error(`[seed] Error inserting into ${table}:`, error.message);
    throw error;
  }
  console.log(`[seed] ✓ Inserted ${data.length} rows into ${table}`);
  return data as T[];
}

// ─── 1. INVESTORS ─────────────────────────────────────────────────────────────

const investorData = [
  {
    name: 'Sequoia Capital',
    slug: 'sequoia-capital',
    type: 'VC',
    bio: 'Sequoia Capital is a venture capital firm that specializes in technology companies. Founded in 1972, it has backed companies like Apple, Google, Oracle, and Airbnb.',
    aum: B(85),
    portfolio_count: 250,
    stage_focus: ['seed', 'series-a', 'series-b', 'growth'],
    sector_focus: ['AI', 'SaaS', 'Fintech', 'Consumer', 'Healthcare'],
    location: 'Menlo Park, CA',
    logo_url: 'https://logo.clearbit.com/sequoiacap.com',
    avg_check_size: M(10),
    fund_number: 22,
  },
  {
    name: 'Andreessen Horowitz (a16z)',
    slug: 'a16z',
    type: 'VC',
    bio: 'Andreessen Horowitz is a Silicon Valley-based venture capital firm. Known for backing Facebook, Twitter, Lyft, and pioneering the "software is eating the world" thesis.',
    aum: B(42),
    portfolio_count: 500,
    stage_focus: ['seed', 'series-a', 'series-b', 'series-c', 'growth'],
    sector_focus: ['AI', 'Crypto', 'Bio', 'SaaS', 'Consumer', 'Fintech'],
    location: 'Menlo Park, CA',
    logo_url: 'https://logo.clearbit.com/a16z.com',
    avg_check_size: M(15),
    fund_number: 9,
  },
  {
    name: 'Lightspeed Venture Partners',
    slug: 'lightspeed',
    type: 'VC',
    bio: 'Lightspeed is a global VC firm with offices in Silicon Valley, India, Israel, and Southeast Asia. Known for early bets on Snap, Affirm, and Mulesoft.',
    aum: B(18),
    portfolio_count: 400,
    stage_focus: ['seed', 'series-a', 'series-b'],
    sector_focus: ['AI', 'Enterprise', 'Consumer', 'Fintech', 'Health'],
    location: 'Menlo Park, CA',
    logo_url: 'https://logo.clearbit.com/lsvp.com',
    avg_check_size: M(8),
    fund_number: 14,
  },
  {
    name: 'Accel',
    slug: 'accel',
    type: 'VC',
    bio: 'Accel is a global venture capital firm that has been backing exceptional founders since 1983. Notable investments include Facebook, Dropbox, Slack, and Spotify.',
    aum: B(20),
    portfolio_count: 350,
    stage_focus: ['seed', 'series-a', 'series-b'],
    sector_focus: ['AI', 'SaaS', 'Cybersecurity', 'Fintech', 'Dev Tools'],
    location: 'Palo Alto, CA',
    logo_url: 'https://logo.clearbit.com/accel.com',
    avg_check_size: M(12),
    fund_number: 16,
  },
  {
    name: 'Tiger Global Management',
    slug: 'tiger-global',
    type: 'VC',
    bio: 'Tiger Global is a global technology-focused investment firm with deep experience in private and public markets.',
    aum: B(58),
    portfolio_count: 900,
    stage_focus: ['series-b', 'series-c', 'growth'],
    sector_focus: ['AI', 'E-commerce', 'Fintech', 'SaaS'],
    location: 'New York, NY',
    logo_url: 'https://logo.clearbit.com/tigerglobal.com',
    avg_check_size: M(50),
    fund_number: 15,
  },
  {
    name: 'Khosla Ventures',
    slug: 'khosla-ventures',
    type: 'VC',
    bio: 'Founded by Sun Microsystems co-founder Vinod Khosla, focused on impactful tech including AI, energy, and biotech.',
    aum: B(15),
    portfolio_count: 200,
    stage_focus: ['seed', 'series-a'],
    sector_focus: ['AI', 'Climate Tech', 'Health', 'Robotics'],
    location: 'Menlo Park, CA',
    logo_url: 'https://logo.clearbit.com/khoslaventures.com',
    avg_check_size: M(5),
    fund_number: 7,
  },
  {
    name: 'General Catalyst',
    slug: 'general-catalyst',
    type: 'VC',
    bio: 'General Catalyst is a venture capital firm focused on powerful transformative technology. Early backer of Airbnb, Stripe, and Snap.',
    aum: B(25),
    portfolio_count: 300,
    stage_focus: ['seed', 'series-a', 'series-b', 'growth'],
    sector_focus: ['AI', 'Health', 'Climate', 'Fintech'],
    location: 'Cambridge, MA',
    logo_url: 'https://logo.clearbit.com/generalcatalyst.com',
    avg_check_size: M(10),
    fund_number: 10,
  },
  {
    name: 'Index Ventures',
    slug: 'index-ventures',
    type: 'VC',
    bio: 'European-rooted VC with global reach. Backed Slack, Figma, Dropbox, and many category-defining companies.',
    aum: B(10),
    portfolio_count: 250,
    stage_focus: ['seed', 'series-a', 'series-b'],
    sector_focus: ['AI', 'SaaS', 'Gaming', 'Fintech'],
    location: 'San Francisco, CA',
    logo_url: 'https://logo.clearbit.com/indexventures.com',
    avg_check_size: M(8),
    fund_number: 11,
  },
  {
    name: 'Coatue Management',
    slug: 'coatue',
    type: 'VC',
    bio: 'Technology-focused investment firm investing across public and private markets. Known for writing large checks at growth stage.',
    aum: B(50),
    portfolio_count: 200,
    stage_focus: ['series-c', 'series-d+', 'growth'],
    sector_focus: ['AI', 'Consumer Tech', 'Fintech', 'SaaS'],
    location: 'New York, NY',
    logo_url: 'https://logo.clearbit.com/coatue.com',
    avg_check_size: M(75),
    fund_number: 8,
  },
  {
    name: 'Spark Capital',
    slug: 'spark-capital',
    type: 'VC',
    bio: 'Spark Capital is a venture firm backing founders from early to growth stage. Invested in Twitter, Tumblr, and Oculus.',
    aum: B(4),
    portfolio_count: 100,
    stage_focus: ['seed', 'series-a'],
    sector_focus: ['AI', 'Consumer', 'Dev Tools', 'Media'],
    location: 'Boston, MA',
    logo_url: 'https://logo.clearbit.com/sparkcapital.com',
    avg_check_size: M(4),
    fund_number: 6,
  },
  {
    name: 'Microsoft M12',
    slug: 'microsoft-m12',
    type: 'Corporate',
    bio: "Microsoft's venture fund focused on AI, cloud infrastructure, and enterprise software.",
    aum: B(2),
    portfolio_count: 80,
    stage_focus: ['series-a', 'series-b', 'series-c'],
    sector_focus: ['AI', 'Cloud', 'Enterprise', 'Dev Tools'],
    location: 'Redmond, WA',
    logo_url: 'https://logo.clearbit.com/microsoft.com',
    avg_check_size: M(15),
    fund_number: 3,
  },
  {
    name: 'Google Ventures (GV)',
    slug: 'gv',
    type: 'Corporate',
    bio: "Alphabet's venture capital arm. Has backed Uber, Slack, Flatiron Health, and many AI-native companies.",
    aum: B(8),
    portfolio_count: 300,
    stage_focus: ['seed', 'series-a', 'series-b'],
    sector_focus: ['AI', 'Life Sciences', 'Consumer', 'Robotics'],
    location: 'Mountain View, CA',
    logo_url: 'https://logo.clearbit.com/gv.com',
    avg_check_size: M(10),
    fund_number: 5,
  },
  {
    name: 'Nvidia GPU Ventures',
    slug: 'nvidia-ventures',
    type: 'Corporate',
    bio: "Nvidia's strategic investment arm focused on AI infrastructure, robotics, and autonomous systems.",
    aum: B(1),
    portfolio_count: 50,
    stage_focus: ['series-a', 'series-b'],
    sector_focus: ['AI Infrastructure', 'Robotics', 'Autonomous', 'HPC'],
    location: 'Santa Clara, CA',
    logo_url: 'https://logo.clearbit.com/nvidia.com',
    avg_check_size: M(20),
    fund_number: 1,
  },
  {
    name: 'Benchmark',
    slug: 'benchmark',
    type: 'VC',
    bio: 'Benchmark is a Silicon Valley VC firm known for concentrated early-stage bets. Backed Uber, Snapchat, Twitter, and Discord.',
    aum: B(3),
    portfolio_count: 120,
    stage_focus: ['seed', 'series-a'],
    sector_focus: ['AI', 'Consumer', 'Enterprise', 'Dev Tools'],
    location: 'San Francisco, CA',
    logo_url: 'https://logo.clearbit.com/benchmark.com',
    avg_check_size: M(5),
    fund_number: 12,
  },
  {
    name: 'Founders Fund',
    slug: 'founders-fund',
    type: 'VC',
    bio: "Peter Thiel's venture firm focused on breakthrough technologies. Early investor in SpaceX, Palantir, and Airbnb.",
    aum: B(11),
    portfolio_count: 100,
    stage_focus: ['seed', 'series-a', 'series-b'],
    sector_focus: ['AI', 'Defense', 'Biotech', 'Space'],
    location: 'San Francisco, CA',
    logo_url: 'https://logo.clearbit.com/foundersfund.com',
    avg_check_size: M(15),
    fund_number: 8,
  },
  {
    name: 'First Round Capital',
    slug: 'first-round',
    type: 'VC',
    bio: 'First Round is a seed-stage venture firm known for its early investments in Uber, Square, and Notion.',
    aum: B(3),
    portfolio_count: 300,
    stage_focus: ['pre-seed', 'seed'],
    sector_focus: ['AI', 'SaaS', 'Consumer', 'Fintech'],
    location: 'San Francisco, CA',
    logo_url: 'https://logo.clearbit.com/firstround.com',
    avg_check_size: M(3),
    fund_number: 5,
  },
  {
    name: 'Insight Partners',
    slug: 'insight-partners',
    type: 'VC',
    bio: 'Insight Partners is a global software VC firm that has invested in 400+ companies including Twitter, Shopify, and Wix.',
    aum: B(90),
    portfolio_count: 700,
    stage_focus: ['series-b', 'series-c', 'growth'],
    sector_focus: ['AI', 'SaaS', 'E-commerce', 'Cybersecurity'],
    location: 'New York, NY',
    logo_url: 'https://logo.clearbit.com/insightpartners.com',
    avg_check_size: M(30),
    fund_number: 13,
  },
  {
    name: 'SoftBank Vision Fund',
    slug: 'softbank-vision-fund',
    type: 'VC',
    bio: "The world's largest technology-focused venture fund, backing companies like WeWork, Arm, and many AI leaders.",
    aum: B(100),
    portfolio_count: 475,
    stage_focus: ['series-c', 'series-d+', 'growth'],
    sector_focus: ['AI', 'Robotics', 'Autonomous', 'Fintech', 'E-commerce'],
    location: 'Tokyo, Japan',
    logo_url: 'https://logo.clearbit.com/softbank.jp',
    avg_check_size: M(300),
    fund_number: 2,
  },
  {
    name: 'NEA',
    slug: 'nea',
    type: 'VC',
    bio: 'New Enterprise Associates is one of the largest VC firms globally, with investments across healthcare and technology.',
    aum: B(25),
    portfolio_count: 500,
    stage_focus: ['seed', 'series-a', 'series-b'],
    sector_focus: ['AI', 'Healthcare', 'SaaS', 'Cybersecurity'],
    location: 'Chevy Chase, MD',
    logo_url: 'https://logo.clearbit.com/nea.com',
    avg_check_size: M(12),
    fund_number: 18,
  },
  {
    name: 'Kleiner Perkins',
    slug: 'kleiner-perkins',
    type: 'VC',
    bio: 'Kleiner Perkins is a legendary VC firm with investments in Google, Amazon, Genentech, and now leading AI companies.',
    aum: B(9),
    portfolio_count: 180,
    stage_focus: ['seed', 'series-a', 'series-b'],
    sector_focus: ['AI', 'Healthcare', 'Climate', 'Consumer'],
    location: 'Menlo Park, CA',
    logo_url: 'https://logo.clearbit.com/kleinerperkins.com',
    avg_check_size: M(8),
    fund_number: 19,
  },
];

// ─── 2. COMPANIES ─────────────────────────────────────────────────────────────

const companyData = [
  {
    name: 'OpenAI',
    slug: 'openai',
    description: 'OpenAI is an AI research and deployment company. Its mission is to ensure that artificial general intelligence benefits all of humanity. Creator of ChatGPT, GPT-4, DALL-E, and Sora.',
    category: 'Large Language Model',
    funding_total: B(17.9),
    employee_count: 1800,
    founded_year: 2015,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/openai.com',
    website: 'https://openai.com',
    stage: 'growth',
    is_unicorn: true,
    valuation: B(157),
    growth_score: 98.5,
    data_confidence_score: 0.99,
  },
  {
    name: 'Anthropic',
    slug: 'anthropic',
    description: 'Anthropic is an AI safety company building reliable, interpretable, and steerable AI systems. Creator of the Claude series of AI assistants.',
    category: 'Large Language Model',
    funding_total: B(7.3),
    employee_count: 850,
    founded_year: 2021,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/anthropic.com',
    website: 'https://anthropic.com',
    stage: 'series-d+',
    is_unicorn: true,
    valuation: B(61.5),
    growth_score: 96.2,
    data_confidence_score: 0.97,
  },
  {
    name: 'Mistral AI',
    slug: 'mistral-ai',
    description: 'Mistral AI is a French AI company building frontier open and closed-source language models. Known for Mistral 7B and Mixtral MoE models.',
    category: 'Large Language Model',
    funding_total: M(1100),
    employee_count: 250,
    founded_year: 2023,
    hq_city: 'Paris',
    hq_country: 'France',
    logo_url: 'https://logo.clearbit.com/mistral.ai',
    website: 'https://mistral.ai',
    stage: 'series-b',
    is_unicorn: true,
    valuation: B(6),
    growth_score: 91.4,
    data_confidence_score: 0.93,
  },
  {
    name: 'Perplexity AI',
    slug: 'perplexity-ai',
    description: 'Perplexity AI is an AI-powered search engine that provides direct answers with citations. It is often called the "answer engine" replacing traditional search.',
    category: 'Search AI',
    funding_total: M(900),
    employee_count: 150,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/perplexity.ai',
    website: 'https://perplexity.ai',
    stage: 'series-c',
    is_unicorn: true,
    valuation: B(9),
    growth_score: 94.7,
    data_confidence_score: 0.92,
  },
  {
    name: 'Cursor',
    slug: 'cursor',
    description: 'Cursor is an AI-first code editor built on VSCode, featuring deep AI integration for code generation, editing, and debugging with GPT-4 and Claude.',
    category: 'Code AI',
    funding_total: M(900),
    employee_count: 100,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/cursor.sh',
    website: 'https://cursor.sh',
    stage: 'series-b',
    is_unicorn: true,
    valuation: B(2.5),
    growth_score: 95.1,
    data_confidence_score: 0.91,
  },
  {
    name: 'Midjourney',
    slug: 'midjourney',
    description: 'Midjourney is an independent research lab that produces an AI program that generates images from natural language descriptions. One of the leading image generation tools.',
    category: 'Image Generation',
    funding_total: 0,
    employee_count: 50,
    founded_year: 2021,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/midjourney.com',
    website: 'https://midjourney.com',
    stage: 'growth',
    is_unicorn: true,
    valuation: B(10),
    growth_score: 88.3,
    data_confidence_score: 0.85,
  },
  {
    name: 'Runway ML',
    slug: 'runway-ml',
    description: 'Runway is an applied AI research company building the next generation of creative tools. Known for Gen-2 and Gen-3 text-to-video models.',
    category: 'Video Generation',
    funding_total: M(400),
    employee_count: 200,
    founded_year: 2018,
    hq_city: 'New York',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/runwayml.com',
    website: 'https://runwayml.com',
    stage: 'series-c',
    is_unicorn: true,
    valuation: B(1.5),
    growth_score: 87.6,
    data_confidence_score: 0.90,
  },
  {
    name: 'Cohere',
    slug: 'cohere',
    description: "Cohere provides enterprise AI models for understanding and generating text. It's the AI platform of choice for developers and enterprises building NLP products.",
    category: 'Large Language Model',
    funding_total: M(970),
    employee_count: 400,
    founded_year: 2019,
    hq_city: 'Toronto',
    hq_country: 'Canada',
    logo_url: 'https://logo.clearbit.com/cohere.com',
    website: 'https://cohere.com',
    stage: 'series-c',
    is_unicorn: true,
    valuation: B(5),
    growth_score: 82.4,
    data_confidence_score: 0.91,
  },
  {
    name: 'Stability AI',
    slug: 'stability-ai',
    description: 'Stability AI is an open-source AI company best known for Stable Diffusion, a text-to-image generation model.',
    category: 'Image Generation',
    funding_total: M(200),
    employee_count: 180,
    founded_year: 2019,
    hq_city: 'London',
    hq_country: 'UK',
    logo_url: 'https://logo.clearbit.com/stability.ai',
    website: 'https://stability.ai',
    stage: 'series-a',
    is_unicorn: true,
    valuation: B(1),
    growth_score: 74.2,
    data_confidence_score: 0.86,
  },
  {
    name: 'Hugging Face',
    slug: 'hugging-face',
    description: 'Hugging Face is the AI community building the future. It hosts the largest collection of ML models, datasets, and demos. Known as the "GitHub of AI".',
    category: 'AI Infrastructure',
    funding_total: M(395),
    employee_count: 350,
    founded_year: 2016,
    hq_city: 'New York',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/huggingface.co',
    website: 'https://huggingface.co',
    stage: 'series-c',
    is_unicorn: true,
    valuation: B(4.5),
    growth_score: 89.1,
    data_confidence_score: 0.95,
  },
  {
    name: 'Scale AI',
    slug: 'scale-ai',
    description: "Scale AI provides data infrastructure for AI, including data labeling, model evaluation, and RLHF pipelines. Powers OpenAI, Google, and the US government's AI programs.",
    category: 'AI Data & Infrastructure',
    funding_total: M(1500),
    employee_count: 800,
    founded_year: 2016,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/scale.com',
    website: 'https://scale.com',
    stage: 'series-e',
    is_unicorn: true,
    valuation: B(13.8),
    growth_score: 85.3,
    data_confidence_score: 0.94,
  },
  {
    name: 'xAI',
    slug: 'xai',
    description: "Elon Musk's AI company building Grok — an AI assistant integrated into X (Twitter) with real-time knowledge. Aims to understand the true nature of the universe.",
    category: 'Large Language Model',
    funding_total: B(6),
    employee_count: 300,
    founded_year: 2023,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/x.ai',
    website: 'https://x.ai',
    stage: 'series-c',
    is_unicorn: true,
    valuation: B(50),
    growth_score: 90.7,
    data_confidence_score: 0.89,
  },
  {
    name: 'Inflection AI',
    slug: 'inflection-ai',
    description: 'Inflection AI was an AI startup building Pi, a personal AI companion. Co-founded by Mustafa Suleyman and Reid Hoffman. Key team joined Microsoft in 2024.',
    category: 'Large Language Model',
    funding_total: B(1.5),
    employee_count: 70,
    founded_year: 2022,
    hq_city: 'Palo Alto',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/inflection.ai',
    website: 'https://inflection.ai',
    stage: 'acquired',
    is_unicorn: true,
    valuation: B(4),
    growth_score: 60.0,
    data_confidence_score: 0.82,
  },
  {
    name: 'Adept AI',
    slug: 'adept-ai',
    description: 'Adept AI is building AI agents that can take actions in software — from browsing the web to operating enterprise software on behalf of users.',
    category: 'AI Agents',
    funding_total: M(415),
    employee_count: 100,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/adept.ai',
    website: 'https://adept.ai',
    stage: 'series-b',
    is_unicorn: false,
    valuation: B(1),
    growth_score: 72.5,
    data_confidence_score: 0.87,
  },
  {
    name: 'Character.AI',
    slug: 'character-ai',
    description: 'Character.AI allows users to create and talk with custom AI characters and personas. One of the most-visited AI consumer apps globally.',
    category: 'AI Companions',
    funding_total: M(750),
    employee_count: 200,
    founded_year: 2021,
    hq_city: 'Menlo Park',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/character.ai',
    website: 'https://character.ai',
    stage: 'series-c',
    is_unicorn: true,
    valuation: B(5),
    growth_score: 86.9,
    data_confidence_score: 0.91,
  },
  {
    name: 'Pika Labs',
    slug: 'pika-labs',
    description: 'Pika Labs is a video generation startup enabling anyone to create videos from text and images using AI. One of the leading text-to-video platforms.',
    category: 'Video Generation',
    funding_total: M(135),
    employee_count: 50,
    founded_year: 2023,
    hq_city: 'Palo Alto',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/pika.art',
    website: 'https://pika.art',
    stage: 'series-b',
    is_unicorn: false,
    valuation: M(700),
    growth_score: 85.4,
    data_confidence_score: 0.88,
  },
  {
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    description: 'ElevenLabs is an AI audio research and deployment company producing highly realistic speech synthesis and voice cloning technology.',
    category: 'Voice AI',
    funding_total: M(280),
    employee_count: 200,
    founded_year: 2022,
    hq_city: 'New York',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/elevenlabs.io',
    website: 'https://elevenlabs.io',
    stage: 'series-c',
    is_unicorn: true,
    valuation: B(3.3),
    growth_score: 93.2,
    data_confidence_score: 0.93,
  },
  {
    name: 'Harvey AI',
    slug: 'harvey-ai',
    description: 'Harvey is an AI legal platform trained on legal cases, contracts, and regulations. Used by top law firms for contract review, due diligence, and legal research.',
    category: 'Legal AI',
    funding_total: M(406),
    employee_count: 200,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/harvey.ai',
    website: 'https://harvey.ai',
    stage: 'series-d',
    is_unicorn: true,
    valuation: B(3),
    growth_score: 89.8,
    data_confidence_score: 0.90,
  },
  {
    name: 'Cognition AI',
    slug: 'cognition-ai',
    description: 'Cognition AI built Devin, the first fully autonomous AI software engineer capable of completing entire coding tasks independently.',
    category: 'Code AI',
    funding_total: M(175),
    employee_count: 50,
    founded_year: 2023,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/cognition.ai',
    website: 'https://cognition.ai',
    stage: 'series-b',
    is_unicorn: true,
    valuation: B(2),
    growth_score: 92.0,
    data_confidence_score: 0.88,
  },
  {
    name: 'Together AI',
    slug: 'together-ai',
    description: 'Together AI is a cloud platform for running and fine-tuning open-source AI models. Known for its fast inference speeds and developer-friendly API.',
    category: 'AI Infrastructure',
    funding_total: M(228),
    employee_count: 100,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/together.ai',
    website: 'https://together.ai',
    stage: 'series-b',
    is_unicorn: false,
    valuation: M(950),
    growth_score: 84.1,
    data_confidence_score: 0.89,
  },
  {
    name: 'Weights & Biases',
    slug: 'weights-and-biases',
    description: 'Weights & Biases (W&B) is the MLOps platform for ML practitioners. Used for experiment tracking, model monitoring, and dataset management.',
    category: 'MLOps',
    funding_total: M(250),
    employee_count: 400,
    founded_year: 2017,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/wandb.ai',
    website: 'https://wandb.ai',
    stage: 'series-c',
    is_unicorn: true,
    valuation: B(1.25),
    growth_score: 80.5,
    data_confidence_score: 0.92,
  },
  {
    name: 'Replicate',
    slug: 'replicate',
    description: "Replicate lets you run AI models in the cloud. It's a platform for deploying and scaling AI models with a single API call.",
    category: 'AI Infrastructure',
    funding_total: M(58),
    employee_count: 30,
    founded_year: 2019,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/replicate.com',
    website: 'https://replicate.com',
    stage: 'series-a',
    is_unicorn: false,
    valuation: M(350),
    growth_score: 79.3,
    data_confidence_score: 0.88,
  },
  {
    name: 'Modal Labs',
    slug: 'modal-labs',
    description: 'Modal is a serverless cloud for AI and data teams. Run GPU-accelerated jobs with zero infrastructure management.',
    category: 'AI Infrastructure',
    funding_total: M(110),
    employee_count: 60,
    founded_year: 2021,
    hq_city: 'New York',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/modal.com',
    website: 'https://modal.com',
    stage: 'series-b',
    is_unicorn: false,
    valuation: M(500),
    growth_score: 83.7,
    data_confidence_score: 0.87,
  },
  {
    name: 'Langchain',
    slug: 'langchain',
    description: 'LangChain is a framework for developing applications powered by language models. The de-facto standard library for LLM application development.',
    category: 'AI Developer Tools',
    funding_total: M(35),
    employee_count: 50,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/langchain.com',
    website: 'https://langchain.com',
    stage: 'series-a',
    is_unicorn: false,
    valuation: M(200),
    growth_score: 81.2,
    data_confidence_score: 0.86,
  },
  {
    name: 'Weaviate',
    slug: 'weaviate',
    description: 'Weaviate is an open-source vector database. It is used to build AI-native applications with semantic search, recommendations, and generative AI features.',
    category: 'AI Infrastructure',
    funding_total: M(68),
    employee_count: 120,
    founded_year: 2019,
    hq_city: 'Amsterdam',
    hq_country: 'Netherlands',
    logo_url: 'https://logo.clearbit.com/weaviate.io',
    website: 'https://weaviate.io',
    stage: 'series-b',
    is_unicorn: false,
    valuation: M(380),
    growth_score: 77.4,
    data_confidence_score: 0.87,
  },
  {
    name: 'Pinecone',
    slug: 'pinecone',
    description: 'Pinecone is a managed vector database that helps developers build real-time, accurate, and scalable AI applications.',
    category: 'AI Infrastructure',
    funding_total: M(138),
    employee_count: 150,
    founded_year: 2019,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/pinecone.io',
    website: 'https://pinecone.io',
    stage: 'series-b',
    is_unicorn: false,
    valuation: M(750),
    growth_score: 78.9,
    data_confidence_score: 0.88,
  },
  {
    name: 'Imbue',
    slug: 'imbue',
    description: 'Imbue (formerly known as Generally Intelligent) is an AI research company building AI agents that can reason and learn like humans.',
    category: 'AI Agents',
    funding_total: M(220),
    employee_count: 60,
    founded_year: 2021,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/imbue.com',
    website: 'https://imbue.com',
    stage: 'series-b',
    is_unicorn: false,
    valuation: B(1),
    growth_score: 74.8,
    data_confidence_score: 0.83,
  },
  {
    name: 'Typeface',
    slug: 'typeface',
    description: 'Typeface is a generative AI platform for enterprise marketing content. It creates on-brand content at scale for Fortune 500 companies.',
    category: 'Marketing AI',
    funding_total: M(165),
    employee_count: 150,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/typeface.ai',
    website: 'https://typeface.ai',
    stage: 'series-b',
    is_unicorn: false,
    valuation: M(1000),
    growth_score: 72.3,
    data_confidence_score: 0.84,
  },
  {
    name: 'Glean',
    slug: 'glean',
    description: "Glean is an AI-powered enterprise search and work assistant. It searches across all of a company's SaaS tools and knowledge bases.",
    category: 'Enterprise AI',
    funding_total: M(360),
    employee_count: 600,
    founded_year: 2019,
    hq_city: 'Palo Alto',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/glean.com',
    website: 'https://glean.com',
    stage: 'series-d',
    is_unicorn: true,
    valuation: B(4.6),
    growth_score: 85.9,
    data_confidence_score: 0.90,
  },
  {
    name: 'Writer',
    slug: 'writer',
    description: 'Writer is an enterprise AI platform for content generation, brand compliance, and document automation. Used by Vanguard, Spotify, and L\'Oréal.',
    category: 'Enterprise AI',
    funding_total: M(326),
    employee_count: 250,
    founded_year: 2020,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/writer.com',
    website: 'https://writer.com',
    stage: 'series-c',
    is_unicorn: true,
    valuation: B(1.9),
    growth_score: 82.6,
    data_confidence_score: 0.89,
  },
  {
    name: 'Replit',
    slug: 'replit',
    description: 'Replit is a browser-based IDE that uses AI to assist coding, generate apps, and deploy software instantly. Popular with developers and students.',
    category: 'Code AI',
    funding_total: M(222),
    employee_count: 200,
    founded_year: 2016,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/replit.com',
    website: 'https://replit.com',
    stage: 'series-b',
    is_unicorn: true,
    valuation: B(1.16),
    growth_score: 78.4,
    data_confidence_score: 0.90,
  },
  {
    name: 'Deepgram',
    slug: 'deepgram',
    description: 'Deepgram provides AI-powered speech recognition APIs with industry-leading accuracy and speed for real-time and batch transcription.',
    category: 'Voice AI',
    funding_total: M(145),
    employee_count: 200,
    founded_year: 2015,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/deepgram.com',
    website: 'https://deepgram.com',
    stage: 'series-c',
    is_unicorn: false,
    valuation: M(750),
    growth_score: 76.3,
    data_confidence_score: 0.88,
  },
  {
    name: 'Descript',
    slug: 'descript',
    description: 'Descript is an AI-powered video and audio editing platform. Edit recordings like a document — delete words to cut footage.',
    category: 'Video AI',
    funding_total: M(100),
    employee_count: 120,
    founded_year: 2017,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/descript.com',
    website: 'https://descript.com',
    stage: 'series-c',
    is_unicorn: false,
    valuation: M(550),
    growth_score: 75.1,
    data_confidence_score: 0.87,
  },
  {
    name: 'Synthesia',
    slug: 'synthesia',
    description: 'Synthesia is an AI video generation platform that creates professional videos from text using AI avatars — no cameras, studios, or actors needed.',
    category: 'Video Generation',
    funding_total: M(157),
    employee_count: 300,
    founded_year: 2017,
    hq_city: 'London',
    hq_country: 'UK',
    logo_url: 'https://logo.clearbit.com/synthesia.io',
    website: 'https://synthesia.io',
    stage: 'series-c',
    is_unicorn: true,
    valuation: B(2.1),
    growth_score: 82.9,
    data_confidence_score: 0.91,
  },
  {
    name: 'Otter.ai',
    slug: 'otter-ai',
    description: 'Otter.ai provides AI-powered meeting transcription, notes, and summaries. Integrates with Zoom, Google Meet, and Microsoft Teams.',
    category: 'Productivity AI',
    funding_total: M(38),
    employee_count: 100,
    founded_year: 2016,
    hq_city: 'Mountain View',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/otter.ai',
    website: 'https://otter.ai',
    stage: 'series-b',
    is_unicorn: false,
    valuation: M(300),
    growth_score: 70.2,
    data_confidence_score: 0.85,
  },
  {
    name: 'Jasper AI',
    slug: 'jasper-ai',
    description: 'Jasper is an AI content creation platform for marketing teams. Generates blog posts, ads, emails, and social content at scale.',
    category: 'Marketing AI',
    funding_total: M(131),
    employee_count: 200,
    founded_year: 2021,
    hq_city: 'Austin',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/jasper.ai',
    website: 'https://jasper.ai',
    stage: 'series-a',
    is_unicorn: true,
    valuation: B(1.5),
    growth_score: 65.4,
    data_confidence_score: 0.87,
  },
  {
    name: 'Coreweave',
    slug: 'coreweave',
    description: 'CoreWeave is a specialized cloud provider delivering massive-scale GPU compute for AI workloads. Operates the largest Nvidia H100/H200 cluster outside hyperscalers.',
    category: 'AI Infrastructure',
    funding_total: B(8.9),
    employee_count: 1000,
    founded_year: 2017,
    hq_city: 'Roseland',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/coreweave.com',
    website: 'https://coreweave.com',
    stage: 'public',
    is_unicorn: true,
    valuation: B(19),
    growth_score: 90.3,
    data_confidence_score: 0.94,
  },
  {
    name: 'Groq',
    slug: 'groq',
    description: 'Groq builds ultra-fast AI inference hardware and cloud services. Its LPU (Language Processing Unit) is the fastest publicly available AI inference chip.',
    category: 'AI Hardware',
    funding_total: M(640),
    employee_count: 400,
    founded_year: 2016,
    hq_city: 'Mountain View',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/groq.com',
    website: 'https://groq.com',
    stage: 'series-d',
    is_unicorn: true,
    valuation: B(2.8),
    growth_score: 92.5,
    data_confidence_score: 0.91,
  },
  {
    name: 'Lambda Labs',
    slug: 'lambda-labs',
    description: 'Lambda is an AI cloud offering affordable GPU compute for training and running AI models, plus its own line of GPU workstations.',
    category: 'AI Infrastructure',
    funding_total: M(920),
    employee_count: 300,
    founded_year: 2012,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/lambdalabs.com',
    website: 'https://lambdalabs.com',
    stage: 'series-c',
    is_unicorn: true,
    valuation: B(1.5),
    growth_score: 83.0,
    data_confidence_score: 0.89,
  },
  {
    name: 'Cerebras Systems',
    slug: 'cerebras-systems',
    description: "Cerebras builds the world's largest chip — the Wafer-Scale Engine — for AI training. Its systems dramatically accelerate deep learning model training.",
    category: 'AI Hardware',
    funding_total: M(720),
    employee_count: 450,
    founded_year: 2016,
    hq_city: 'Sunnyvale',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/cerebras.net',
    website: 'https://cerebras.net',
    stage: 'series-f',
    is_unicorn: true,
    valuation: B(4.25),
    growth_score: 80.8,
    data_confidence_score: 0.90,
  },
  {
    name: 'Abnormal Security',
    slug: 'abnormal-security',
    description: 'Abnormal Security uses AI to detect and stop email-based cyberattacks — including phishing, business email compromise, and supply chain attacks.',
    category: 'AI Security',
    funding_total: M(619),
    employee_count: 650,
    founded_year: 2018,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/abnormalsecurity.com',
    website: 'https://abnormalsecurity.com',
    stage: 'series-d',
    is_unicorn: true,
    valuation: B(5.1),
    growth_score: 83.6,
    data_confidence_score: 0.91,
  },
  {
    name: 'Abridge',
    slug: 'abridge',
    description: 'Abridge uses generative AI to turn doctor-patient conversations into clinical notes in real-time, reducing physician burnout.',
    category: 'Healthcare AI',
    funding_total: M(212),
    employee_count: 180,
    founded_year: 2018,
    hq_city: 'Pittsburgh',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/abridge.com',
    website: 'https://abridge.com',
    stage: 'series-c',
    is_unicorn: false,
    valuation: M(850),
    growth_score: 87.4,
    data_confidence_score: 0.88,
  },
  {
    name: 'Suno AI',
    slug: 'suno-ai',
    description: 'Suno AI generates high-quality, full-length songs from a text prompt — lyrics, vocals, and instruments. Used by millions of music creators.',
    category: 'Music Generation',
    funding_total: M(125),
    employee_count: 30,
    founded_year: 2023,
    hq_city: 'Cambridge',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/suno.com',
    website: 'https://suno.com',
    stage: 'series-b',
    is_unicorn: false,
    valuation: M(500),
    growth_score: 88.6,
    data_confidence_score: 0.87,
  },
  {
    name: 'Udio',
    slug: 'udio',
    description: 'Udio is a music generation AI that creates professional-quality songs from prompts. Co-founded by former Google DeepMind researchers.',
    category: 'Music Generation',
    funding_total: M(50),
    employee_count: 20,
    founded_year: 2023,
    hq_city: 'New York',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/udio.com',
    website: 'https://udio.com',
    stage: 'seed',
    is_unicorn: false,
    valuation: M(200),
    growth_score: 82.1,
    data_confidence_score: 0.83,
  },
  {
    name: 'Sierra AI',
    slug: 'sierra-ai',
    description: 'Sierra builds conversational AI agents for enterprise customer support, co-founded by Bret Taylor and Clay Bavor.',
    category: 'Enterprise AI',
    funding_total: M(285),
    employee_count: 200,
    founded_year: 2023,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/sierra.ai',
    website: 'https://sierra.ai',
    stage: 'series-b',
    is_unicorn: true,
    valuation: B(4.5),
    growth_score: 91.3,
    data_confidence_score: 0.89,
  },
  {
    name: 'Luma AI',
    slug: 'luma-ai',
    description: 'Luma AI creates 3D captures and video generation. Known for Dream Machine, a high-quality text-to-video model, and NeRF-based 3D scene reconstruction.',
    category: 'Video Generation',
    funding_total: M(65),
    employee_count: 60,
    founded_year: 2021,
    hq_city: 'Palo Alto',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/lumalabs.ai',
    website: 'https://lumalabs.ai',
    stage: 'series-b',
    is_unicorn: false,
    valuation: M(400),
    growth_score: 84.7,
    data_confidence_score: 0.86,
  },
  {
    name: 'Kling AI',
    slug: 'kling-ai',
    description: 'Kling AI is a video generation platform by Kuaishou Technology capable of generating realistic, high-definition 2-minute videos from text and images.',
    category: 'Video Generation',
    funding_total: B(5),
    employee_count: 2000,
    founded_year: 2023,
    hq_city: 'Beijing',
    hq_country: 'China',
    logo_url: 'https://logo.clearbit.com/klingai.com',
    website: 'https://klingai.com',
    stage: 'series-c',
    is_unicorn: true,
    valuation: B(8),
    growth_score: 87.3,
    data_confidence_score: 0.84,
  },
  {
    name: 'DeepSeek',
    slug: 'deepseek',
    description: 'DeepSeek is a Chinese AI lab that shocked the AI world with its open-source DeepSeek-R1 model, rivaling OpenAI at a fraction of the training cost.',
    category: 'Large Language Model',
    funding_total: B(1.3),
    employee_count: 1000,
    founded_year: 2023,
    hq_city: 'Hangzhou',
    hq_country: 'China',
    logo_url: 'https://logo.clearbit.com/deepseek.com',
    website: 'https://deepseek.com',
    stage: 'series-b',
    is_unicorn: true,
    valuation: B(12),
    growth_score: 96.8,
    data_confidence_score: 0.88,
  },
  {
    name: '01.AI',
    slug: '01ai',
    description: '01.AI is an AI company founded by Kai-Fu Lee, building Yi-series open-source LLMs. One of the fastest unicorn companies in history.',
    category: 'Large Language Model',
    funding_total: M(200),
    employee_count: 100,
    founded_year: 2023,
    hq_city: 'Beijing',
    hq_country: 'China',
    logo_url: 'https://logo.clearbit.com/01.ai',
    website: 'https://01.ai',
    stage: 'series-a',
    is_unicorn: true,
    valuation: B(1),
    growth_score: 79.1,
    data_confidence_score: 0.81,
  },
];

// ─── 3. FOUNDERS ─────────────────────────────────────────────────────────────

// Generated after companies are inserted — maps slug → id
function buildFounders(companyIdMap: Record<string, string>) {
  return [
    { name: 'Sam Altman', slug: 'sam-altman', title: 'CEO', company_id: companyIdMap['openai'], bio: 'CEO of OpenAI. Former President of Y Combinator.', twitter: '@sama', linkedin: 'samaltman', location: 'San Francisco, CA', photo_url: 'https://i.pravatar.cc/150?u=samaltman' },
    { name: 'Greg Brockman', slug: 'greg-brockman', title: 'President', company_id: companyIdMap['openai'], bio: 'President and co-founder of OpenAI. Former CTO of Stripe.', twitter: '@gdb', linkedin: 'gregbrockman', location: 'San Francisco, CA', photo_url: 'https://i.pravatar.cc/150?u=gregbrockman' },
    { name: 'Dario Amodei', slug: 'dario-amodei', title: 'CEO', company_id: companyIdMap['anthropic'], bio: 'CEO of Anthropic. Former VP of Research at OpenAI.', twitter: '@DarioAmodei', linkedin: 'darioamodei', location: 'San Francisco, CA', photo_url: 'https://i.pravatar.cc/150?u=darioamodei' },
    { name: 'Daniela Amodei', slug: 'daniela-amodei', title: 'President', company_id: companyIdMap['anthropic'], bio: 'President of Anthropic. Former VP of Operations at OpenAI.', twitter: '@danielaamodei', linkedin: 'danielaamodei', location: 'San Francisco, CA', photo_url: 'https://i.pravatar.cc/150?u=danielaamodei' },
    { name: 'Arthur Mensch', slug: 'arthur-mensch', title: 'CEO', company_id: companyIdMap['mistral-ai'], bio: 'CEO of Mistral AI. Former researcher at Google DeepMind.', twitter: '@arthurmensch', linkedin: 'arthurmensch', location: 'Paris, France', photo_url: 'https://i.pravatar.cc/150?u=arthurmensch' },
    { name: 'Aravind Srinivas', slug: 'aravind-srinivas', title: 'CEO', company_id: companyIdMap['perplexity-ai'], bio: 'CEO of Perplexity AI. Former researcher at OpenAI and DeepMind.', twitter: '@AravSrinivas', linkedin: 'aravindsrinivas', location: 'San Francisco, CA', photo_url: 'https://i.pravatar.cc/150?u=aravindsrinivas' },
    { name: 'Michael Truell', slug: 'michael-truell', title: 'CEO', company_id: companyIdMap['cursor'], bio: 'CEO of Cursor / Anysphere. MIT graduate, building the future of software development.', twitter: '@truell20', linkedin: 'michaeltruell', location: 'San Francisco, CA', photo_url: 'https://i.pravatar.cc/150?u=michaeltruell' },
    { name: 'David Holz', slug: 'david-holz', title: 'Founder', company_id: companyIdMap['midjourney'], bio: 'Founder of Midjourney and co-founder of Leap Motion. Physics researcher turned AI artist.', twitter: '@davidholz_', linkedin: 'davidholz', location: 'San Francisco, CA', photo_url: 'https://i.pravatar.cc/150?u=davidholz' },
    { name: 'Cristóbal Valenzuela', slug: 'cristobal-valenzuela', title: 'CEO', company_id: companyIdMap['runway-ml'], bio: 'CEO of Runway. Artist and technologist building creative AI tools.', twitter: '@c_valenzuela', linkedin: 'cristobalvalenzuela', location: 'New York, NY', photo_url: 'https://i.pravatar.cc/150?u=cvalenzuela' },
    { name: 'Aidan Gomez', slug: 'aidan-gomez', title: 'CEO', company_id: companyIdMap['cohere'], bio: 'CEO of Cohere. Co-author of "Attention Is All You Need" (Transformer paper).', twitter: '@aidangomez', linkedin: 'aidangomez', location: 'Toronto, Canada', photo_url: 'https://i.pravatar.cc/150?u=aidangomez' },
    { name: 'Emad Mostaque', slug: 'emad-mostaque', title: 'Former CEO', company_id: companyIdMap['stability-ai'], bio: 'Founder of Stability AI. Resigned in 2024, open-source AI advocate.', twitter: '@EMostaque', linkedin: 'emadmostaque', location: 'London, UK', photo_url: 'https://i.pravatar.cc/150?u=emadmostaque' },
    { name: 'Clement Delangue', slug: 'clement-delangue', title: 'CEO', company_id: companyIdMap['hugging-face'], bio: 'CEO of Hugging Face. Serial entrepreneur building the open AI community.', twitter: '@ClementDelangue', linkedin: 'clementdelangue', location: 'New York, NY', photo_url: 'https://i.pravatar.cc/150?u=clementdelangue' },
    { name: 'Alexandr Wang', slug: 'alexandr-wang', title: 'CEO', company_id: companyIdMap['scale-ai'], bio: 'CEO of Scale AI. Youngest self-made billionaire. Former MIT student.', twitter: '@alexandr_wang', linkedin: 'alexandrwang', location: 'San Francisco, CA', photo_url: 'https://i.pravatar.cc/150?u=alexandrwang' },
    { name: 'Elon Musk', slug: 'elon-musk', title: 'CEO', company_id: companyIdMap['xai'], bio: 'CEO of xAI, Tesla, SpaceX. Former OpenAI co-founder. Owner of X.', twitter: '@elonmusk', linkedin: 'elonmusk', location: 'Austin, TX', photo_url: 'https://i.pravatar.cc/150?u=elonmusk' },
    { name: 'Fei-Fei Li', slug: 'fei-fei-li', title: 'Co-CEO', company_id: companyIdMap['character-ai'], bio: 'Computer vision pioneer, Stanford AI Lab director. Co-founded World Labs.', twitter: '@drfeifei', linkedin: 'feifei-li', location: 'Stanford, CA', photo_url: 'https://i.pravatar.cc/150?u=feifeili' },
    { name: 'Scott Stephenson', slug: 'scott-stephenson-deepgram', title: 'CEO', company_id: companyIdMap['deepgram'], bio: 'CEO of Deepgram. Physics PhD turned speech AI entrepreneur.', twitter: '@scottastephenson', linkedin: 'scottastephenson', location: 'San Francisco, CA', photo_url: 'https://i.pravatar.cc/150?u=scottstephenson' },
    { name: 'Winston Weinberg', slug: 'winston-weinberg', title: 'CEO', company_id: companyIdMap['harvey-ai'], bio: 'CEO of Harvey AI. Former attorney at O\'Melveny & Myers. Stanford Law.', twitter: '@winstonweinberg', linkedin: 'winstonweinberg', location: 'San Francisco, CA', photo_url: 'https://i.pravatar.cc/150?u=winstonweinberg' },
    { name: 'Scott Wu', slug: 'scott-wu', title: 'CEO', company_id: companyIdMap['cognition-ai'], bio: 'CEO of Cognition AI, creator of Devin. ICPC World Finalist.', twitter: '@scottwu_devin', linkedin: 'scottwu', location: 'San Francisco, CA', photo_url: 'https://i.pravatar.cc/150?u=scottwu' },
    { name: 'Mati Staniszewski', slug: 'mati-staniszewski', title: 'CEO', company_id: companyIdMap['elevenlabs'], bio: 'CEO of ElevenLabs. Grew up in Poland, built a global voice AI empire.', twitter: '@MatiStaniszewski', linkedin: 'matistaniszewski', location: 'New York, NY', photo_url: 'https://i.pravatar.cc/150?u=matistaniszewski' },
    { name: 'Vipul Ved Prakash', slug: 'vipul-ved-prakash', title: 'CEO', company_id: companyIdMap['together-ai'], bio: 'CEO of Together AI. Pioneer of social web, now building AI infrastructure.', twitter: '@vipul', linkedin: 'vipulvedprakash', location: 'San Francisco, CA', photo_url: 'https://i.pravatar.cc/150?u=vipulvedprakash' },
    { name: 'Bret Taylor', slug: 'bret-taylor', title: 'CEO', company_id: companyIdMap['sierra-ai'], bio: 'CEO of Sierra AI. Former Salesforce Co-CEO, Twitter Chairman, Google Maps co-creator.', twitter: '@btaylor', linkedin: 'brettaylor', location: 'San Francisco, CA', photo_url: 'https://i.pravatar.cc/150?u=brettaylor' },
    { name: 'Mike Mignano', slug: 'mike-mignano-suno', title: 'CEO', company_id: companyIdMap['suno-ai'], bio: 'CEO of Suno AI. Former Head of Talk at Spotify.', twitter: '@mignano', linkedin: 'mikemignano', location: 'Cambridge, MA', photo_url: 'https://i.pravatar.cc/150?u=mikemignano' },
    { name: 'Liang Wenfeng', slug: 'liang-wenfeng', title: 'CEO', company_id: companyIdMap['deepseek'], bio: 'CEO of DeepSeek and founder of High-Flyer Quant hedge fund. Shook the AI world in January 2025.', twitter: '@liangwenfeng', linkedin: 'liangwenfeng', location: 'Hangzhou, China', photo_url: 'https://i.pravatar.cc/150?u=liangwenfeng' },
    { name: 'Jonathan Ross', slug: 'jonathan-ross', title: 'CEO', company_id: companyIdMap['groq'], bio: 'CEO of Groq. Created the first Google TPU while at Google X.', twitter: '@jonrossQL', linkedin: 'jonross', location: 'Mountain View, CA', photo_url: 'https://i.pravatar.cc/150?u=jonathanross' },
  ].filter((f) => f.company_id); // Skip founders whose company wasn't seeded
}

// ─── 4. PRODUCTS ─────────────────────────────────────────────────────────────

function buildProducts(companyIdMap: Record<string, string>) {
  return [
    { company_id: companyIdMap['openai'], name: 'ChatGPT', description: 'The world\'s most popular AI chatbot. Conversational AI powered by GPT-4o.', category: 'Chatbot', launch_date: '2022-11-30', upvotes: 98500, website_url: 'https://chat.openai.com' },
    { company_id: companyIdMap['openai'], name: 'GPT-4o API', description: 'Multimodal LLM API for developers. Supports text, vision, and audio.', category: 'API', launch_date: '2024-05-13', upvotes: 72000, website_url: 'https://platform.openai.com' },
    { company_id: companyIdMap['openai'], name: 'DALL-E 3', description: 'State-of-the-art text-to-image generation integrated into ChatGPT.', category: 'Image Generation', launch_date: '2023-10-01', upvotes: 45000, website_url: 'https://openai.com/dall-e-3' },
    { company_id: companyIdMap['openai'], name: 'Sora', description: 'Text-to-video generation model capable of creating 1-minute HD videos from prompts.', category: 'Video Generation', launch_date: '2024-02-15', upvotes: 68000, website_url: 'https://sora.com' },
    { company_id: companyIdMap['anthropic'], name: 'Claude 3.5 Sonnet', description: 'Anthropic\'s most capable and intelligent AI model. Best in class for coding and analysis.', category: 'LLM', launch_date: '2024-06-20', upvotes: 55000, website_url: 'https://claude.ai' },
    { company_id: companyIdMap['anthropic'], name: 'Claude API', description: 'Enterprise-grade AI API with constitutional AI safety built-in.', category: 'API', launch_date: '2023-03-14', upvotes: 42000, website_url: 'https://docs.anthropic.com' },
    { company_id: companyIdMap['mistral-ai'], name: 'Mistral Large', description: 'Mistral\'s flagship closed model, competing with GPT-4 on benchmarks.', category: 'LLM', launch_date: '2024-02-26', upvotes: 28000, website_url: 'https://mistral.ai' },
    { company_id: companyIdMap['mistral-ai'], name: 'Mixtral 8x7B', description: 'Open-source sparse mixture-of-experts model. Beats LLaMA 2 70B on most benchmarks.', category: 'Open Source LLM', launch_date: '2023-12-11', upvotes: 38000, website_url: 'https://huggingface.co/mistralai' },
    { company_id: companyIdMap['perplexity-ai'], name: 'Perplexity Search', description: 'AI-powered search with real-time web access and cited answers.', category: 'Search', launch_date: '2022-12-01', upvotes: 52000, website_url: 'https://perplexity.ai' },
    { company_id: companyIdMap['perplexity-ai'], name: 'Perplexity Pro', description: 'Premium search with access to GPT-4, Claude, and custom models.', category: 'Subscription', launch_date: '2023-08-01', upvotes: 22000, website_url: 'https://perplexity.ai/pro' },
    { company_id: companyIdMap['cursor'], name: 'Cursor Editor', description: 'AI-native code editor with inline generation, multi-file editing, and chat.', category: 'IDE', launch_date: '2023-01-15', upvotes: 61000, website_url: 'https://cursor.sh' },
    { company_id: companyIdMap['midjourney'], name: 'Midjourney V6', description: 'The most photorealistic AI image generation model. Available via Discord.', category: 'Image Generation', launch_date: '2023-12-20', upvotes: 72000, website_url: 'https://midjourney.com' },
    { company_id: companyIdMap['runway-ml'], name: 'Gen-3 Alpha', description: 'High-quality text-to-video model with cinematic control and motion.', category: 'Video Generation', launch_date: '2024-06-17', upvotes: 35000, website_url: 'https://runwayml.com/gen-3' },
    { company_id: companyIdMap['elevenlabs'], name: 'ElevenLabs Voice Cloning', description: 'Clone any voice from a 1-minute sample with near-perfect accuracy.', category: 'Voice AI', launch_date: '2023-01-23', upvotes: 48000, website_url: 'https://elevenlabs.io' },
    { company_id: companyIdMap['elevenlabs'], name: 'ElevenLabs Reader', description: 'Turn any article or PDF into an audio podcast with AI voice narration.', category: 'Mobile App', launch_date: '2024-03-01', upvotes: 22000, website_url: 'https://elevenlabs.io/reader' },
    { company_id: companyIdMap['xai'], name: 'Grok 2', description: 'AI assistant integrated into X with real-time social media knowledge.', category: 'Chatbot', launch_date: '2024-08-13', upvotes: 33000, website_url: 'https://x.ai/grok' },
    { company_id: companyIdMap['hugging-face'], name: 'HuggingFace Hub', description: 'The model hub hosting 500,000+ AI models. GitHub for AI.', category: 'Platform', launch_date: '2019-10-01', upvotes: 89000, website_url: 'https://huggingface.co/models' },
    { company_id: companyIdMap['cognition-ai'], name: 'Devin', description: 'The first fully autonomous AI software engineer. Can plan, code, test, and deploy.', category: 'AI Agent', launch_date: '2024-03-12', upvotes: 78000, website_url: 'https://devin.ai' },
    { company_id: companyIdMap['groq'], name: 'GroqCloud', description: 'Fastest AI inference in the cloud. Run LLaMA, Mixtral at 500+ tokens/sec.', category: 'API', launch_date: '2024-01-15', upvotes: 41000, website_url: 'https://console.groq.com' },
    { company_id: companyIdMap['suno-ai'], name: 'Suno v3', description: 'Generate complete songs with vocals, lyrics, and instrumentals from a text prompt.', category: 'Music Generation', launch_date: '2024-03-21', upvotes: 46000, website_url: 'https://suno.com' },
    { company_id: companyIdMap['deepseek'], name: 'DeepSeek-R1', description: 'Open-source reasoning model rivaling OpenAI o1 at 95% lower training cost.', category: 'Open Source LLM', launch_date: '2025-01-20', upvotes: 91000, website_url: 'https://deepseek.com/r1' },
  ].filter((p) => p.company_id);
}

// ─── 5. NEWS ARTICLES ─────────────────────────────────────────────────────────

function buildNews(companyIdMap: Record<string, string>) {
  const c = companyIdMap;
  const articles = [
    { title: 'OpenAI raises $6.6B at $157B valuation in largest AI funding round ever', url: 'https://techcrunch.com/2024/10/02/openai-raises-6-6b', published_at: '2024-10-02', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['openai']], summary: 'OpenAI closed its largest funding round ever, bringing its valuation to $157 billion. Investors include Thrive Capital, Microsoft, and SoftBank.' },
    { title: 'Anthropic raises $4B from Amazon in landmark AI partnership', url: 'https://www.anthropic.com/news/amazon-investment', published_at: '2023-09-25', source: 'Anthropic Blog', tag: 'Funding', related_company_ids: [c['anthropic']], summary: 'Amazon will invest up to $4 billion in Anthropic and become a primary cloud provider, with Anthropic using AWS Trainium and Inferentia chips.' },
    { title: 'Mistral AI raises €600M Series B, valued at $6B', url: 'https://techcrunch.com/2024/06/11/mistral-ai-raises-e600m', published_at: '2024-06-11', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['mistral-ai']], summary: 'French AI startup Mistral AI raised €600M in a Series B led by General Catalyst, cementing its position as Europe\'s leading AI lab.' },
    { title: 'Perplexity AI valued at $9B as it raises $250M Series D', url: 'https://www.perplexity.ai/blog/series-d', published_at: '2024-12-19', source: 'Perplexity Blog', tag: 'Funding', related_company_ids: [c['perplexity-ai']], summary: 'Perplexity AI raised $250M at a $9B valuation, with investors including IVP, NEA, and Databricks CEO Ali Ghodsi.' },
    { title: 'Cursor reaches $400M ARR, raises $900M at $9.9B valuation', url: 'https://techcrunch.com/2025/01/10/cursor-anysphere-900m', published_at: '2025-01-10', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['cursor']], summary: 'Anysphere, the company behind Cursor, raised $900M in a round led by Thrive Capital, with participation from a16z and Accel.' },
    { title: 'DeepSeek R1 shocks AI industry: matches OpenAI o1 at fraction of the cost', url: 'https://www.deepseek.com/news/r1-launch', published_at: '2025-01-20', source: 'DeepSeek Blog', tag: 'Research', related_company_ids: [c['deepseek'], c['openai']], summary: 'DeepSeek released R1, an open-source reasoning model trained for $5.6M that matches GPT-o1 on math and coding benchmarks, triggering a massive market reaction.' },
    { title: 'ElevenLabs raises $80M Series B, now valued at $1.1B', url: 'https://techcrunch.com/2024/01/22/elevenlabs-raises-80m', published_at: '2024-01-22', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['elevenlabs']], summary: 'Voice AI startup ElevenLabs closed its Series B round, becoming a unicorn just two years after launch.' },
    { title: 'Groq achieves 500 tokens/sec on LLaMA 3 — 10x faster than GPU', url: 'https://blog.groq.com/lpu-speed', published_at: '2024-04-18', source: 'Groq Blog', tag: 'Product', related_company_ids: [c['groq']], summary: 'Groq demonstrated LLM inference at 500 tokens per second using its LPU architecture, dramatically outperforming Nvidia GPU-based alternatives.' },
    { title: 'Cognition releases Devin, the first fully autonomous AI software engineer', url: 'https://cognition.ai/blog/introducing-devin', published_at: '2024-03-12', source: 'Cognition Blog', tag: 'Product', related_company_ids: [c['cognition-ai']], summary: 'Cognition AI unveiled Devin, an AI agent capable of completing real engineering tasks on Upwork, including bug fixes, feature development, and deployment.' },
    { title: 'Scale AI signs $1B government contract to provide AI for US military', url: 'https://techcrunch.com/2024/09/01/scale-ai-government-contract', published_at: '2024-09-01', source: 'TechCrunch', tag: 'Partnership', related_company_ids: [c['scale-ai']], summary: 'Scale AI secured a major contract with the US Department of Defense to provide data infrastructure and AI model evaluation for defense applications.' },
    { title: 'OpenAI launches GPT-4o: free multimodal AI for everyone', url: 'https://openai.com/index/hello-gpt-4o', published_at: '2024-05-13', source: 'OpenAI Blog', tag: 'Product', related_company_ids: [c['openai']], summary: 'OpenAI announced GPT-4o, a new flagship model combining text, audio, and vision in a single model, available for free to ChatGPT users.' },
    { title: 'Runway Gen-3 Alpha sets new benchmark for AI video generation', url: 'https://runwayml.com/blog/introducing-gen-3', published_at: '2024-06-17', source: 'Runway Blog', tag: 'Product', related_company_ids: [c['runway-ml']], summary: 'Runway released Gen-3 Alpha with dramatically improved consistency, motion, and fidelity compared to Gen-2.' },
    { title: 'Hugging Face surpasses 1 million models on its platform', url: 'https://huggingface.co/blog/1m-models', published_at: '2024-09-12', source: 'Hugging Face Blog', tag: 'Milestone', related_company_ids: [c['hugging-face']], summary: 'The AI model hub hit a significant milestone, hosting over 1 million open-source models from researchers and developers worldwide.' },
    { title: 'Google makes $300M investment in Anthropic as AI race heats up', url: 'https://www.cnbc.com/2023/02/03/google-investing-300-million-anthropic.html', published_at: '2023-02-03', source: 'CNBC', tag: 'Funding', related_company_ids: [c['anthropic']], summary: 'Google committed to investing $300M in AI safety startup Anthropic as part of a broader cloud partnership, competing with Microsoft\'s OpenAI partnership.' },
    { title: 'Cursor vs GitHub Copilot: the battle for the AI code editor market', url: 'https://techcrunch.com/2024/07/15/cursor-vs-copilot', published_at: '2024-07-15', source: 'TechCrunch', tag: 'Analysis', related_company_ids: [c['cursor']], summary: 'As Cursor\'s ARR skyrockets, GitHub Copilot faces serious competition from an AI-native editor designed around LLMs from the ground up.' },
    { title: 'Midjourney V6 arrives with unprecedented photorealism', url: 'https://midjourney.com/blog/v6-launch', published_at: '2023-12-20', source: 'Midjourney Blog', tag: 'Product', related_company_ids: [c['midjourney']], summary: 'Midjourney V6 introduces vastly improved prompt adherence, text rendering in images, and photorealistic image quality.' },
    { title: 'Mistral releases Mixtral 8x7B: open-source beats GPT-3.5', url: 'https://mistral.ai/news/mixtral-of-experts', published_at: '2023-12-11', source: 'Mistral Blog', tag: 'Research', related_company_ids: [c['mistral-ai']], summary: 'Mistral dropped Mixtral 8x7B without announcement via torrent, an open sparse MoE model that outperforms LLaMA 2 70B and GPT-3.5 on most benchmarks.' },
    { title: 'Sierra AI emerges from stealth with $285M and $4.5B valuation', url: 'https://techcrunch.com/2024/02/sierra-ai-launch', published_at: '2024-02-20', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['sierra-ai']], summary: 'Sierra, co-founded by Bret Taylor and Clay Bavor, launched publicly with $285M raised and partnerships with major enterprise customers.' },
    { title: 'Suno v3 generates complete songs in seconds — music industry reacts', url: 'https://techcrunch.com/2024/03/22/suno-v3-music-ai', published_at: '2024-03-22', source: 'TechCrunch', tag: 'Product', related_company_ids: [c['suno-ai'], c['udio']], summary: 'Suno v3 generates professional-quality songs from a text prompt in under 20 seconds, sparking debates about AI copyright in the music industry.' },
    { title: 'CoreWeave IPO raises $1.5B, valued at $19B on Nasdaq', url: 'https://wsj.com/coreweave-ipo', published_at: '2025-03-28', source: 'WSJ', tag: 'IPO', related_company_ids: [c['coreweave']], summary: 'GPU cloud provider CoreWeave went public on Nasdaq, raising $1.5B in one of the largest tech IPOs of 2025. The company supplies GPUs to OpenAI and Microsoft.' },
    { title: 'Harvey AI raises $300M at $3B valuation to bring AI to BigLaw', url: 'https://techcrunch.com/2024/11/harvey-ai-300m', published_at: '2024-11-14', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['harvey-ai']], summary: 'Harvey AI raised $300M in a round led by Sequoia Capital, with participation from Google Ventures and OpenAI\'s fund.' },
    { title: 'Pika Labs raises $80M Series B to build next-gen video AI', url: 'https://techcrunch.com/2024/02/pika-series-b', published_at: '2024-02-06', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['pika-labs'], c['runway-ml']], summary: 'Pika Labs secured $80M as text-to-video AI competition intensifies with Runway, Sora, and Kling all vying for market leadership.' },
    { title: 'Glean raises $260M at $4.6B valuation for enterprise AI search', url: 'https://techcrunch.com/2024/08/glean-260m', published_at: '2024-08-26', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['glean']], summary: 'Glean\'s enterprise AI search platform hit $100M ARR and raised $260M in a round co-led by Kleiner Perkins and Lightspeed.' },
    { title: 'Abridge lands $150M to deploy AI medical scribe across hospital systems', url: 'https://techcrunch.com/2024/02/abridge-150m', published_at: '2024-02-23', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['abridge']], summary: 'Abridge raised $150M to expand its AI clinical documentation platform, with deployments at UPMC, Kaiser Permanente, and Emory Healthcare.' },
    { title: 'a16z leads $23B in AI investments in 2024 — a record year', url: 'https://a16z.com/ai-investments-2024', published_at: '2024-12-31', source: 'a16z Blog', tag: 'Industry', related_company_ids: [c['openai'], c['anthropic'], c['mistral-ai']], summary: 'Andreessen Horowitz deployed a record $23 billion across AI investments in 2024, backing infrastructure, application, and frontier model companies.' },
    { title: 'Sequoia\'s AI thesis: the $600B question every startup must answer', url: 'https://sequoiacap.com/ai-600b', published_at: '2024-09-05', source: 'Sequoia Blog', tag: 'Analysis', related_company_ids: [c['openai'], c['anthropic'], c['cursor'], c['perplexity-ai']], summary: 'Sequoia partner David Cahn asks whether AI companies can generate enough revenue to justify their infrastructure costs and valuations.' },
    { title: 'Together AI raises $106M to democratize open-source AI compute', url: 'https://techcrunch.com/2023/11/together-ai-series-a', published_at: '2023-11-29', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['together-ai'], c['hugging-face']], summary: 'Together AI raised a $106M Series A to build fast and affordable inference for open-source models like LLaMA, Mistral, and Stable Diffusion.' },
    { title: 'Synthesia raises $90M to bring AI video to every enterprise', url: 'https://techcrunch.com/2023/06/synthesia-90m', published_at: '2023-06-13', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['synthesia']], summary: 'London-based Synthesia closed its Series C to scale its AI avatar video platform, used by over 50,000 businesses.' },
    { title: 'Cohere raises $500M as enterprise AI boom drives demand for private LLMs', url: 'https://techcrunch.com/2024/07/cohere-500m', published_at: '2024-07-22', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['cohere']], summary: 'Cohere raised $500M to build enterprise-grade LLMs with private deployment options, competing with OpenAI\'s Enterprise tier.' },
    { title: 'OpenAI vs Anthropic: the $200B AI safety race', url: 'https://wired.com/openai-vs-anthropic', published_at: '2024-10-15', source: 'Wired', tag: 'Analysis', related_company_ids: [c['openai'], c['anthropic']], summary: 'A deep dive into how two former allies — with fundamentally different safety philosophies — are racing to build the most powerful AI in history.' },
    { title: 'Cerebras raises $250M, plans IPO as AI chip race intensifies', url: 'https://techcrunch.com/2024/09/cerebras-250m-ipo', published_at: '2024-09-19', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['cerebras-systems'], c['groq']], summary: 'Cerebras Systems filed for IPO and raised an additional $250M as companies compete to dethrone Nvidia in the AI training chip market.' },
    { title: 'Scale AI and Anthropic partner to accelerate RLHF', url: 'https://scale.com/blog/anthropic-partnership', published_at: '2023-07-11', source: 'Scale Blog', tag: 'Partnership', related_company_ids: [c['scale-ai'], c['anthropic']], summary: 'Scale AI and Anthropic partnered to use Scale\'s data platform for reinforcement learning from human feedback (RLHF) to train Claude models.' },
    { title: 'Hugging Face and AWS announce $100M partnership for open-source AI', url: 'https://huggingface.co/blog/aws-partnership', published_at: '2023-11-28', source: 'Hugging Face Blog', tag: 'Partnership', related_company_ids: [c['hugging-face']], summary: 'Amazon Web Services and Hugging Face partnered to make open-source AI models more accessible on AWS SageMaker.' },
    { title: 'ElevenLabs launches AI dubbing for 29 languages — Netflix takes notice', url: 'https://elevenlabs.io/blog/dubbing', published_at: '2024-03-20', source: 'ElevenLabs Blog', tag: 'Product', related_company_ids: [c['elevenlabs']], summary: 'ElevenLabs launched AI dubbing that preserves tone and emotion across 29 languages, attracting interest from film studios and streaming platforms.' },
    { title: 'xAI open-sources Grok-1: 314B parameter MoE model', url: 'https://x.ai/blog/grok-os', published_at: '2024-03-17', source: 'xAI Blog', tag: 'Research', related_company_ids: [c['xai']], summary: 'Elon Musk\'s xAI released the weights of Grok-1 under Apache 2.0 license, making it the largest open-source model at the time.' },
    { title: 'Perplexity vs Google: can an AI startup dethrone the search giant?', url: 'https://theverge.com/perplexity-vs-google', published_at: '2024-06-10', source: 'The Verge', tag: 'Analysis', related_company_ids: [c['perplexity-ai']], summary: 'With 100M monthly active users, Perplexity AI is positioning itself as a direct challenger to Google Search among Gen Z and tech-savvy users.' },
    { title: 'Abnormal Security raises $250M at $5.1B valuation', url: 'https://techcrunch.com/2024/08/abnormal-250m', published_at: '2024-08-06', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['abnormal-security']], summary: 'AI cybersecurity company Abnormal Security raised $250M, with 2,000+ enterprise customers and $200M ARR.' },
    { title: 'Stability AI faces financial turmoil as Emad Mostaque resigns', url: 'https://techcrunch.com/2024/03/stability-ai-mostaque-resign', published_at: '2024-03-23', source: 'TechCrunch', tag: 'Company News', related_company_ids: [c['stability-ai']], summary: 'Stability AI CEO Emad Mostaque resigned amid reports of financial difficulties, board disputes, and missed payroll for employees.' },
    { title: 'Luma AI Dream Machine goes viral: free text-to-video AI stuns creators', url: 'https://techcrunch.com/2024/06/luma-dream-machine', published_at: '2024-06-12', source: 'TechCrunch', tag: 'Product', related_company_ids: [c['luma-ai'], c['runway-ml'], c['pika-labs']], summary: 'Luma AI launched Dream Machine, a free text-to-video model that went viral on social media, generating 1M videos in its first week.' },
    { title: 'Kling AI goes global: Kuaishou launches its video generator in 100 countries', url: 'https://techcrunch.com/2024/09/kling-global', published_at: '2024-09-10', source: 'TechCrunch', tag: 'Product', related_company_ids: [c['kling-ai'], c['runway-ml'], c['pika-labs'], c['luma-ai']], summary: 'Kuaishou\'s Kling AI video generator expands globally with 1080p video generation, directly challenging Sora and Runway Gen-3.' },
    { title: 'The AI coding wars: Cursor, Devin, Replit battle for $10B market', url: 'https://wired.com/ai-coding-wars', published_at: '2024-08-05', source: 'Wired', tag: 'Analysis', related_company_ids: [c['cursor'], c['cognition-ai'], c['replit']], summary: 'A new generation of AI coding tools is threatening to replace traditional IDEs and freelance developers alike.' },
    { title: 'Pinecone raises $100M as vector database market explodes with AI demand', url: 'https://techcrunch.com/2023/04/pinecone-100m', published_at: '2023-04-27', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['pinecone'], c['weaviate']], summary: 'Pinecone secured $100M as demand for vector databases skyrockets with the rise of RAG architectures in enterprise AI applications.' },
    { title: 'Weaviate raises $50M Series B from Salesforce Ventures and others', url: 'https://techcrunch.com/2023/11/weaviate-50m', published_at: '2023-11-09', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['weaviate']], summary: 'Open-source vector database Weaviate raised $50M to expand its managed cloud offering and compete with Pinecone.' },
    { title: 'Sierra AI signs Siemens, Weight Watchers as enterprise AI agents go mainstream', url: 'https://techcrunch.com/2024/05/sierra-enterprise', published_at: '2024-05-15', source: 'TechCrunch', tag: 'Partnership', related_company_ids: [c['sierra-ai']], summary: 'Sierra AI announced major enterprise customers and revealed its agents handle millions of support interactions per month.' },
    { title: 'DeepSeek triggers $1T stock wipeout as US AI stocks crash', url: 'https://wsj.com/deepseek-stock-market-impact', published_at: '2025-01-27', source: 'WSJ', tag: 'Industry', related_company_ids: [c['deepseek'], c['openai'], c['anthropic']], summary: 'DeepSeek\'s R1 caused Nvidia to lose $600B in market cap in a single day as investors questioned the moat of US AI companies.' },
    { title: 'Groq partners with Meta to provide LLaMA 3 inference at scale', url: 'https://blog.groq.com/meta-partnership', published_at: '2024-04-18', source: 'Groq Blog', tag: 'Partnership', related_company_ids: [c['groq'], c['together-ai']], summary: 'Groq announced a partnership to be one of the primary inference providers for Meta\'s LLaMA 3 models.' },
    { title: 'Cerebras and CoreWeave sign $2B compute partnership', url: 'https://techcrunch.com/2024/08/cerebras-coreweave-deal', published_at: '2024-08-21', source: 'TechCrunch', tag: 'Partnership', related_company_ids: [c['cerebras-systems'], c['coreweave']], summary: 'Cerebras and CoreWeave announced a $2B partnership to deploy Cerebras\' wafer-scale chips in CoreWeave\'s data centers.' },
    { title: 'Lambda Labs vs CoreWeave: GPU cloud war for AI supremacy', url: 'https://techcrunch.com/2024/11/gpu-cloud-war', published_at: '2024-11-18', source: 'TechCrunch', tag: 'Analysis', related_company_ids: [c['lambda-labs'], c['coreweave']], summary: 'As Nvidia H100 supply tightens, Lambda Labs and CoreWeave are competing for billions in GPU cloud contracts from AI startups.' },
    { title: 'Writer raises $200M to dominate enterprise generative AI', url: 'https://techcrunch.com/2024/09/writer-200m', published_at: '2024-09-04', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['writer']], summary: 'Writer closed a $200M funding round with backing from Iconiq Capital, growing 6x year-over-year.' },
    { title: 'Descript acquires podcast editing startup Podcast.ai', url: 'https://descript.com/blog/acquisition', published_at: '2024-04-10', source: 'Descript Blog', tag: 'Acquisition', related_company_ids: [c['descript']], summary: 'Descript acquired AI podcast editing tools to strengthen its position in the audio creation space.' },
    { title: 'Replit launches Replit Agent: AI that builds full-stack apps from scratch', url: 'https://blog.replit.com/agent', published_at: '2024-09-09', source: 'Replit Blog', tag: 'Product', related_company_ids: [c['replit'], c['cursor'], c['cognition-ai']], summary: 'Replit Agent can design, build, and deploy complete web applications from a single text prompt, targeting non-technical builders.' },
    { title: 'LangChain raises $25M as developer tools for LLMs hit mainstream', url: 'https://techcrunch.com/2023/10/langchain-25m', published_at: '2023-10-25', source: 'TechCrunch', tag: 'Funding', related_company_ids: [c['langchain']], summary: 'LangChain raised $25M from Sequoia as the open-source library became the default framework for building LLM applications.' },
    { title: 'Weights & Biases crosses $100M ARR as MLOps becomes essential', url: 'https://wandb.ai/blog/100m-arr', published_at: '2024-06-18', source: 'W&B Blog', tag: 'Milestone', related_company_ids: [c['weights-and-biases']], summary: 'Weights & Biases crossed $100M ARR milestone as every major AI team adopted its experiment tracking platform.' },
    { title: 'Glean expands to 100 enterprise customers and $100M ARR', url: 'https://glean.com/blog/100m-arr', published_at: '2024-07-10', source: 'Glean Blog', tag: 'Milestone', related_company_ids: [c['glean']], summary: 'Enterprise AI search startup Glean reached $100M ARR with customers including Databricks, Grammarly, and Palo Alto Networks.' },
  ].filter((a) => a.related_company_ids.every(Boolean)); // Only include articles where all company IDs resolved

  return articles;
}

// ─── MAIN ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log('\n🌱  GraphOne Seed Script Starting\n');

  // 1. Investors
  console.log('📊 Seeding investors…');
  const investors = await insert('investors', investorData);
  const investorIdMap: Record<string, string> = Object.fromEntries(
    investors.map((i: Record<string, unknown>) => [i.slug as string, i.id as string])
  );

  // 2. Companies
  console.log('\n🏢 Seeding companies…');
  const companies = await insert('companies', companyData);
  const companyIdMap: Record<string, string> = Object.fromEntries(
    companies.map((c: Record<string, unknown>) => [c.slug as string, c.id as string])
  );

  // 3. Founders
  console.log('\n👤 Seeding founders…');
  const founderRows = buildFounders(companyIdMap);
  await insert('founders', founderRows);

  // 4. Products
  console.log('\n📦 Seeding products…');
  const productRows = buildProducts(companyIdMap);
  await insert('products', productRows);

  // 5. Funding rounds
  console.log('\n💰 Seeding funding rounds…');
  const fundingRounds = [
    { company_id: companyIdMap['openai'], round_type: 'series-a', amount: M(1000), currency: 'USD', date: '2023-01-23', lead_investor_id: investorIdMap['microsoft-m12'], co_investors: [] },
    { company_id: companyIdMap['openai'], round_type: 'growth', amount: B(6.6), currency: 'USD', date: '2024-10-02', lead_investor_id: investorIdMap['softbank-vision-fund'], co_investors: [investorIdMap['tiger-global'], investorIdMap['microsoft-m12']].filter(Boolean) },
    { company_id: companyIdMap['anthropic'], round_type: 'series-c', amount: B(4), currency: 'USD', date: '2023-09-25', lead_investor_id: null, co_investors: [investorIdMap['gv'], investorIdMap['spark-capital']].filter(Boolean) },
    { company_id: companyIdMap['anthropic'], round_type: 'series-d', amount: M(750), currency: 'USD', date: '2024-04-09', lead_investor_id: investorIdMap['a16z'], co_investors: [investorIdMap['gv'], investorIdMap['sequoia-capital']].filter(Boolean) },
    { company_id: companyIdMap['mistral-ai'], round_type: 'seed', amount: M(113), currency: 'EUR', date: '2023-06-12', lead_investor_id: investorIdMap['lightspeed'], co_investors: [] },
    { company_id: companyIdMap['mistral-ai'], round_type: 'series-b', amount: M(600), currency: 'EUR', date: '2024-06-11', lead_investor_id: investorIdMap['general-catalyst'], co_investors: [investorIdMap['a16z']].filter(Boolean) },
    { company_id: companyIdMap['perplexity-ai'], round_type: 'series-b', amount: M(73.6), currency: 'USD', date: '2024-01-04', lead_investor_id: investorIdMap['institutional-venture-partners'], co_investors: [investorIdMap['nvidia-ventures']].filter(Boolean) },
    { company_id: companyIdMap['perplexity-ai'], round_type: 'series-d', amount: M(250), currency: 'USD', date: '2024-12-19', lead_investor_id: null, co_investors: [investorIdMap['softbank-vision-fund']].filter(Boolean) },
    { company_id: companyIdMap['cursor'], round_type: 'series-b', amount: M(900), currency: 'USD', date: '2025-01-10', lead_investor_id: null, co_investors: [investorIdMap['a16z'], investorIdMap['accel']].filter(Boolean) },
    { company_id: companyIdMap['scale-ai'], round_type: 'series-e', amount: M(1000), currency: 'USD', date: '2024-05-23', lead_investor_id: investorIdMap['accel'], co_investors: [investorIdMap['a16z'], investorIdMap['tiger-global']].filter(Boolean) },
    { company_id: companyIdMap['hugging-face'], round_type: 'series-d', amount: M(235), currency: 'USD', date: '2023-08-24', lead_investor_id: investorIdMap['a16z'], co_investors: [investorIdMap['sequoia-capital'], investorIdMap['google-ventures']].filter(Boolean) },
    { company_id: companyIdMap['elevenlabs'], round_type: 'series-b', amount: M(80), currency: 'USD', date: '2024-01-22', lead_investor_id: investorIdMap['a16z'], co_investors: [investorIdMap['sequoia-capital']].filter(Boolean) },
    { company_id: companyIdMap['elevenlabs'], round_type: 'series-c', amount: M(180), currency: 'USD', date: '2024-12-12', lead_investor_id: investorIdMap['iconiq-capital'], co_investors: [] },
    { company_id: companyIdMap['harvey-ai'], round_type: 'series-d', amount: M(300), currency: 'USD', date: '2024-11-14', lead_investor_id: investorIdMap['sequoia-capital'], co_investors: [investorIdMap['gv']].filter(Boolean) },
    { company_id: companyIdMap['cognition-ai'], round_type: 'series-b', amount: M(175), currency: 'USD', date: '2024-04-01', lead_investor_id: investorIdMap['founders-fund'], co_investors: [investorIdMap['a16z']].filter(Boolean) },
    { company_id: companyIdMap['groq'], round_type: 'series-d', amount: M(640), currency: 'USD', date: '2024-08-05', lead_investor_id: investorIdMap['tiger-global'], co_investors: [investorIdMap['sequoia-capital']].filter(Boolean) },
    { company_id: companyIdMap['glean'], round_type: 'series-d', amount: M(260), currency: 'USD', date: '2024-08-26', lead_investor_id: investorIdMap['kleiner-perkins'], co_investors: [investorIdMap['lightspeed']].filter(Boolean) },
    { company_id: companyIdMap['together-ai'], round_type: 'series-a', amount: M(106), currency: 'USD', date: '2023-11-29', lead_investor_id: investorIdMap['a16z'], co_investors: [] },
    { company_id: companyIdMap['cohere'], round_type: 'series-c', amount: M(500), currency: 'USD', date: '2024-07-22', lead_investor_id: null, co_investors: [investorIdMap['nvidia-ventures']].filter(Boolean) },
    { company_id: companyIdMap['sierra-ai'], round_type: 'series-b', amount: M(175), currency: 'USD', date: '2024-10-10', lead_investor_id: investorIdMap['sequoia-capital'], co_investors: [] },
    { company_id: companyIdMap['coreweave'], round_type: 'series-c', amount: B(7.5), currency: 'USD', date: '2024-05-30', lead_investor_id: investorIdMap['coatue'], co_investors: [investorIdMap['accel']].filter(Boolean) },
    { company_id: companyIdMap['langchain'], round_type: 'series-a', amount: M(25), currency: 'USD', date: '2023-10-25', lead_investor_id: investorIdMap['sequoia-capital'], co_investors: [] },
    { company_id: companyIdMap['xai'], round_type: 'series-c', amount: B(6), currency: 'USD', date: '2024-11-18', lead_investor_id: null, co_investors: [investorIdMap['a16z'], investorIdMap['sequoia-capital']].filter(Boolean) },
    { company_id: companyIdMap['abnormal-security'], round_type: 'series-d', amount: M(250), currency: 'USD', date: '2024-08-06', lead_investor_id: investorIdMap['wellington-management'], co_investors: [investorIdMap['accel']].filter(Boolean) },
    { company_id: companyIdMap['writer'], round_type: 'series-c', amount: M(200), currency: 'USD', date: '2024-09-04', lead_investor_id: null, co_investors: [investorIdMap['a16z']].filter(Boolean) },
    { company_id: companyIdMap['suno-ai'], round_type: 'series-b', amount: M(125), currency: 'USD', date: '2024-05-21', lead_investor_id: investorIdMap['lightspeed'], co_investors: [] },
    { company_id: companyIdMap['deepseek'], round_type: 'series-b', amount: B(1.3), currency: 'USD', date: '2024-08-28', lead_investor_id: null, co_investors: [] },
  ].filter((r) => r.company_id);

  await insert('funding_rounds', fundingRounds);

  // 6. News articles
  console.log('\n📰 Seeding news articles…');
  const newsRows = buildNews(companyIdMap);
  await insert('news_articles', newsRows);

  // 7. Company relationships
  console.log('\n🔗 Seeding company relationships…');
  const relationships = [
    // LLM competitors
    { company_id: companyIdMap['openai'],      related_company_id: companyIdMap['anthropic'],    relationship_type: 'competitor' },
    { company_id: companyIdMap['openai'],      related_company_id: companyIdMap['mistral-ai'],   relationship_type: 'competitor' },
    { company_id: companyIdMap['openai'],      related_company_id: companyIdMap['xai'],          relationship_type: 'competitor' },
    { company_id: companyIdMap['openai'],      related_company_id: companyIdMap['deepseek'],     relationship_type: 'competitor' },
    { company_id: companyIdMap['anthropic'],   related_company_id: companyIdMap['mistral-ai'],   relationship_type: 'competitor' },
    { company_id: companyIdMap['anthropic'],   related_company_id: companyIdMap['cohere'],       relationship_type: 'competitor' },
    { company_id: companyIdMap['deepseek'],    related_company_id: companyIdMap['mistral-ai'],   relationship_type: 'competitor' },
    // Code AI competitors
    { company_id: companyIdMap['cursor'],      related_company_id: companyIdMap['cognition-ai'], relationship_type: 'competitor' },
    { company_id: companyIdMap['cursor'],      related_company_id: companyIdMap['replit'],       relationship_type: 'competitor' },
    { company_id: companyIdMap['cognition-ai'],related_company_id: companyIdMap['replit'],       relationship_type: 'competitor' },
    // Video generation competitors
    { company_id: companyIdMap['runway-ml'],   related_company_id: companyIdMap['pika-labs'],    relationship_type: 'competitor' },
    { company_id: companyIdMap['runway-ml'],   related_company_id: companyIdMap['luma-ai'],      relationship_type: 'competitor' },
    { company_id: companyIdMap['runway-ml'],   related_company_id: companyIdMap['kling-ai'],     relationship_type: 'competitor' },
    { company_id: companyIdMap['pika-labs'],   related_company_id: companyIdMap['luma-ai'],      relationship_type: 'competitor' },
    // Image generation competitors
    { company_id: companyIdMap['midjourney'],  related_company_id: companyIdMap['stability-ai'], relationship_type: 'competitor' },
    // Music generation competitors
    { company_id: companyIdMap['suno-ai'],     related_company_id: companyIdMap['udio'],         relationship_type: 'competitor' },
    // AI Infrastructure competitors
    { company_id: companyIdMap['groq'],        related_company_id: companyIdMap['cerebras-systems'], relationship_type: 'competitor' },
    { company_id: companyIdMap['coreweave'],   related_company_id: companyIdMap['lambda-labs'],  relationship_type: 'competitor' },
    { company_id: companyIdMap['pinecone'],    related_company_id: companyIdMap['weaviate'],     relationship_type: 'competitor' },
    // Voice AI competitors
    { company_id: companyIdMap['elevenlabs'],  related_company_id: companyIdMap['deepgram'],     relationship_type: 'competitor' },
    // Search AI
    { company_id: companyIdMap['perplexity-ai'], related_company_id: companyIdMap['cursor'],    relationship_type: 'partner' },
    // Partners
    { company_id: companyIdMap['scale-ai'],    related_company_id: companyIdMap['anthropic'],    relationship_type: 'partner' },
    { company_id: companyIdMap['scale-ai'],    related_company_id: companyIdMap['openai'],       relationship_type: 'partner' },
    { company_id: companyIdMap['coreweave'],   related_company_id: companyIdMap['openai'],       relationship_type: 'partner' },
    { company_id: companyIdMap['coreweave'],   related_company_id: companyIdMap['cerebras-systems'], relationship_type: 'partner' },
    { company_id: companyIdMap['groq'],        related_company_id: companyIdMap['together-ai'],  relationship_type: 'partner' },
    { company_id: companyIdMap['hugging-face'], related_company_id: companyIdMap['together-ai'], relationship_type: 'partner' },
    { company_id: companyIdMap['langchain'],   related_company_id: companyIdMap['openai'],       relationship_type: 'partner' },
    { company_id: companyIdMap['langchain'],   related_company_id: companyIdMap['anthropic'],    relationship_type: 'partner' },
    { company_id: companyIdMap['langchain'],   related_company_id: companyIdMap['weaviate'],     relationship_type: 'partner' },
    { company_id: companyIdMap['langchain'],   related_company_id: companyIdMap['pinecone'],     relationship_type: 'partner' },
    { company_id: companyIdMap['harvey-ai'],   related_company_id: companyIdMap['openai'],       relationship_type: 'partner' },
    { company_id: companyIdMap['glean'],       related_company_id: companyIdMap['openai'],       relationship_type: 'partner' },
    { company_id: companyIdMap['glean'],       related_company_id: companyIdMap['anthropic'],    relationship_type: 'partner' },
    { company_id: companyIdMap['weights-and-biases'], related_company_id: companyIdMap['hugging-face'], relationship_type: 'partner' },
  ].filter((r) => r.company_id && r.related_company_id);

  await insert('company_relationships', relationships);

  // 8. Tags
  console.log('\n🏷️  Seeding tags…');
  const tags = [
    { name: 'Large Language Model', slug: 'llm' },
    { name: 'Image Generation', slug: 'image-generation' },
    { name: 'Video Generation', slug: 'video-generation' },
    { name: 'Voice AI', slug: 'voice-ai' },
    { name: 'Code AI', slug: 'code-ai' },
    { name: 'AI Agents', slug: 'ai-agents' },
    { name: 'AI Infrastructure', slug: 'ai-infrastructure' },
    { name: 'Enterprise AI', slug: 'enterprise-ai' },
    { name: 'AI Hardware', slug: 'ai-hardware' },
    { name: 'MLOps', slug: 'mlops' },
    { name: 'Healthcare AI', slug: 'healthcare-ai' },
    { name: 'Legal AI', slug: 'legal-ai' },
    { name: 'Marketing AI', slug: 'marketing-ai' },
    { name: 'Music Generation', slug: 'music-generation' },
    { name: 'Search AI', slug: 'search-ai' },
    { name: 'AI Safety', slug: 'ai-safety' },
    { name: 'Open Source AI', slug: 'open-source-ai' },
    { name: 'Unicorn', slug: 'unicorn' },
  ];
  await insert('tags', tags);

  console.log('\n✅  Seed complete! GraphOne database is ready.\n');
  console.log(`   Investors:             ${investors.length}`);
  console.log(`   Companies:            ${companies.length}`);
  console.log(`   Founders:             ${founderRows.length}`);
  console.log(`   Products:             ${productRows.length}`);
  console.log(`   Funding rounds:       ${fundingRounds.length}`);
  console.log(`   News articles:        ${newsRows.length}`);
  console.log(`   Company relationships: ${relationships.length}`);
}

main().catch((err) => {
  console.error('\n❌  Seed failed:', err);
  process.exit(1);
});
